apiVersion: v1
kind: Service
metadata:
  name: hello-spring-boot-actuator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-spring-boot-actuator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-boot-actuator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-boot-actuator
  template:
    metadata:
      labels:
        app: hello-spring-boot-actuator
    spec:
      containers:
      - name: hello-spring-boot-actuator
        image: ravij/springboot-actuator-jenkins:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
